### PR TITLE
optimize webpack config for using HTML bundler plugin

### PR DESCRIPTION
**Pull request by webdiscus**
Hello @cengizilhan,

I'm the author of the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) and the [webpack-remove-empty-scripts](https://github.com/webdiscus/webpack-remove-empty-scripts) plugins.

I will help you to configure the Webpack using the new powerful `html-bundler-webpack-plugin` instead of `html-webpack-plugin`. This plugin doesn't generate [empty JS files](https://stackoverflow.com/questions/78609865/why-my-scss-files-generated-also-js-extension-scss-css-and-js/78611372) with the same CSS filename.

## Note

- the entrypoint a template file, not JS
- SCSS and TS source files you can define directly in HTML using a relative path or webpack aliases
- the plugin resolves source files of styles, scripts, images, fonts, etc. in templates and replaces them in the generated HTML with output filenames 

This plugin replaces the functionality of the plugins and loaders:
- html-webpack-plugin
- mini-css-extract-plugin
- webpack-remove-empty-scripts
- html-loader
- style-loader
- many other [plugins and loaders](https://github.com/Ben-Long50/homepage/compare/main...webdiscus:ben-long50-homepage:main?expand=1#list-of-plugins)

## P.S.

If you have a question, I can help you with your Webpack Boilerplate.

### CODE REVIEW

**Comment by webdiscus** [comment]
please see the changes in the `Static/src/` directory

**Review by cengizilhan — APPROVED** [review]

**Comment by cengizilhan** [comment]
Hi webdiscus!
Thank you for your help.
I tried it.
I guess its working as bundler / merge files right?
Actually i have too much scss files and js also, and i wanna just export for example 1000 scss file to css dist. 
So its looking like bundle technique right? If i am not wrong.

webpack-remove-empty-scripts is solved my problem.  (awesome script :) thanks )

https://stackoverflow.com/questions/78609865/why-my-scss-files-generated-also-js-extension-scss-css-and-js/78611372?noredirect=1#comment138596223_78611372

What you think which one is better / easy solution?

İm not use single page application.
I have too much js files and scss. 

Exporting only the js files I specified in the entry to the same path works for me.

webpack is actually something that works with single page / bundler logic. For this reason, I think it is a little more difficult to do something like this.

**Comment by webdiscus** [comment]
@cengizilhan 

if you need to compile many SCSS to CSS and JS files (I think it is a lib for a frontend), then of cause you can define all SCSS and JS files in the Webpack `entry` option.
The bundler plugin extracts CSS form source SCSS and save into separate file, like mini-css-extract-plugin, but doesn't generate an empty JS file for each CSS file.

Also if you define any template file in the bundler plugin `entry` option, then this template will be rendered into HTML and all source SCSS and JS defined in HTML will be extracted.

The bundler plugin works for all your use cases.

But, the plugin can't merge many SCSS files defined in entry into single CSS file. You should import needed SCSS files into one file.

```js
{
  entry: {
    'styleA': ['style1.scss', 'style2.scss'], // <= this doesn't works
    'styleB': 'style3.scss', // <= plugin extracts only single defined file
    ...
  }
}
```

You should import all scss files into one `styleA.scss`:
```scss
@import 'style1.scss';
@import 'style2.scss';
```
then 

```js
{
  entry: {
    'styleA': 'styleA.scss', // <= this works fine
    'styleB': 'style3.scss', // <= plugin extracts only single defined file
    ...
  }
}
```

**Comment by cengizilhan** [comment]
thank you so much @webdiscus 
that informations very helpful

**Pull request merged**
